# Site settings
title: valencia.io
email: jupegarnica@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Where creativity meets code

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://valencia.io" # the base hostname & protocol for your site
permalink:   /:categories/:title/


twitter_username: vlc_io
github_username:  Valencia-io

safe: false
exclude:
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
# Build settings
markdown: kramdown
#markdown: redcarpet
2sass:
  style: compressed

# plugins
gems:
  - jekyll-sitemap

# links
collections:
  projects:
    output: true
    permalink: /project/:path/

# defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "blankpage"
      author: "jupegarnica"
  -
    scope:
      path: "project"
      type: projects
    values:
      layout: "project"
      title: write here the name of the project
      repo: https://project.com/repository.git
      description: 72 characters description
      goals:
        - main goal
        - secundary goal
      technology:
        - HTML
        - CSS
      leader: who is the product owner?
      status: open

# Site owner
owner:
  name: Your Name
  avatar: bio-photo.jpg
  email: you@email.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
